image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: |
      npm install
      npm install -g eas-cli
    command: echo "Ready to build your APK!"

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
