name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (apk or aab)'
        required: true
        default: 'apk'
        type: choice
        options:
          - apk
          - aab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Setup EAS
        run: |
          echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" > .env
          echo "Building ${{ github.event.inputs.build_type }} for Android"

      - name: Build Android package
        run: |
          if [[ "${{ github.event.inputs.build_type }}" == "apk" ]]; then
            eas build --platform android --profile preview --non-interactive --no-wait
          else
            eas build --platform android --profile production --non-interactive --no-wait
          fi

      - name: Provide download instructions
        run: |
          echo "Build started! The APK will be available for download from your Expo dashboard."
          echo "Visit https://expo.dev to download the built app when it's ready."
